spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}
  secret-key: ${JWT_SECRET_KEY}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}

app:
  fast-api:
    base-url: ${FAST_API_BASE_URL}
  od-say:
    base-url: ${OD_SAY_BASE_URL}
    api-key: ${OD_SAY_API_KEY}
  kakao-map-api:
    base-url: ${KAKAO_MAP_API_BASE_URL}
    api-key: ${KAKAO_MAP_API_KEY}
  data-go:
    base-url: ${DATA_GO_BASE_URL}
    service-key: ${DATA_GO_SERVICE_KEY}

server:
  address: 0.0.0.0
  port: 8000